### ISSUE TITLE
Roles of bootContext.p1 and bootContext.p2

### ISSUE THREAD

**Issue by haochenuw** [kimandrik/HEAANBOOT#10]
Can you explain the roles of the two polynomials in the code? They do not appear in the paper. Thanks!

**Comment by HanKyoohyung** [comment]
Those polynomials are used in "Scheme::evalExpAndEqual" function which are pre-computed constant complex values (those are needed because we evaluate exponent function in complex field instead of evaluating sin and cos)

In Context.cpp, you can find following codes:

for (i = 0; i < slots; ++i) {
	pvals[i] = 0.0;
	pvals[i + slots].real(0);
	pvals[i + slots].imag(-c);
}

p1.SetLength(N);
fftSpecialInv(pvals, dslots);
for (i = 0, jdx = Nh, idx = 0; i < dslots; ++i, jdx += dgap, idx += dgap) {
	p1.rep[idx] = EvaluatorUtils::scaleUpToZZ(pvals[i].real(), logp);
	p1.rep[jdx] = EvaluatorUtils::scaleUpToZZ(pvals[i].imag(), logp);
}

**Comment by haochenuw** [comment]
I still don't understand: p1 and p2 are not used in the case where numslot = N/2. Can you explain why the difference? In the paper there is no p1 and p2, can you define rigourously the procedures for bootstrapping sparsely packed ciphertexts?

**Comment by kimandrik** [comment]
Hello

This is corresponds to packing the real coefficients of m(x) into complex slots. If numslot < N/2 we can pack all coefficients of real m(x) (numslot * 2 coefficients are different from zero) into numslot * 2 slots (we doing it using p1 and p2) and calculate exponent function only for one ciphertext. In case numslot = N/2 we cannot put all real coefficients of m(x) (N coefficients are different from zero) in one ciphertext with real coefficients. So we calculate exponent for two ciphertexts cipher and c2.

About your second question divByPo2AndEqual or reScaleByAndEqual this is the bug, thanks we have to make them both same). It does not influence the result however, as in the end of bootstrapAndEqual function we artificially set cipher.logp = logp.

**Comment by haochenuw** [comment]
Thanks for the reply. I am still not sure how you use p1 and p2 to pack the coefficients. You multiply by p1 and p2 after the exp evaluation, not before. Did you pack them during the coeffToSlot instead? Am I missing something?
