### ISSUE TITLE
Scaling in evalExpAndEqual

### ISSUE THREAD

**Issue by haochenuw** [kimandrik/HEAANBOOT#12]
https://github.com/kimandrik/HEAANBOOT/blob/923d4410c556b70718c2ea9b872ba2346f72cde5/HEAANBOOT/src/Scheme.cpp#L1144-L1145

scaling by c = 1/(4pi) is done only for the first and last case, but not for the middle one. What's the reason?

**Comment by kimandrik** [comment]
The information about c is in p1 and p2 for the middle case
