### ISSUE TITLE
Meaning of logT and logI in the evalExpAndEqual function

### ISSUE THREAD

**Issue by haochenuw** [kimandrik/HEAANBOOT#5]
Hello! I was wondering the meaning of logT and logI. It seems that logT + logI is equal to the "r" parameter in the cited paper. And I don't quite understand the meaning of logT and logI individually. 
In the procedure, there is a place where the ciphertext is divided by T. Could you explain the reason? Thank you!

**Comment by kimandrik** [comment]
Hello!

For our ciphertext we have b(x) + a(x) * s(x) = m(x) mod q. So for some polynomial I(x) we have b(x) + a(x) * s(x) = m(x) + q * I(x). As s(x) is sparse (h = 64) coefficients of I(x) are not so big, and w.h.p. less than 16, so our logI is normally equal to 4

In EvalExp algorithm, we have to divide our message by 2^r, but in the beginning, we artificially changed our cipher.logp to logq + 4(actually logI) (Scheme.cpp line 1164) which also can be treated as division by 2^logI without loss of precision. So we only have to divide by 2^logT in the EvalExp algorithm. logT parameter should be removed from the code actually, and replaced by (r - logI) to match the paper, but we forgot to do it :(

**Comment by haochenuw** [comment]
Thanks a lot! I am wondering about the effect of logI. Say we set logI = 3 (so the coefficient of I(X) can be greater than 2**logI), then what will happen? Maybe the resulting plaintext precision will be worse, but by how much?

**Comment by kimandrik** [comment]
I think its better to decrease logT, rather than logI. We calculated the theoretical bound of plaintext precision bits for specific parameter sets, and for different logT, you have to calculate it by yourself, cuz the exact formula is huge.
